---
- name: Create Firewall Action
  hosts: localhost

  vars:
  - firewall_action_dro_name: "{{ 'Firewall Action'|urlencode }}"
  - association_hrefs: []
  
  tasks:
    
  - name: Change the service name
    uri:
      url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
      method: POST
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
      body:
        action: edit
        resource:
          name: "{{ ipaddress }}"
          description: "Firewall Action {{ ipaddress }}"
    register: output
    
  - name: Find the "Firewall Action" DRO definition
    uri:
      url: "{{ manageiq.api_url }}/api/generic_object_definitions?expand=resources&filter[]=name='{{ firewall_action_dro_name }}'"
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
    register: action_dro_definition
    
  - set_fact:
      action_dro_definition_href: "{{ action_dro_definition.json.resources[0].href }}"
  
  #- debug: var=action_dro_definition_href
  
  - name: Lookup the "Firewall Group" DRO supplied in the dialog
    uri:
      url: "{{ manageiq.api_url }}/api/generic_objects?expand=resources&filter[]=name='{{ firewall_group_name|urlencode }}'"
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
    register: group_dro
    
  - set_fact:
      group_dro_href: "{{ group_dro.json.resources[0].href }}"
      
  #- debug: var=group_dro_href
  
  - name: Lookup the requesting user
    uri:
      url: "{{ manageiq.api_url }}/api/{{ manageiq.user }}"
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
    register: requester
    
  - set_fact:
      requester_name: "{{ requester.json.name | default('') }}"
      requester_email: "{{ requester.json.email | default('') }}"

  - name: Lookup the user's group
    uri:
      url: "{{ manageiq.api_url }}/api/{{ manageiq.group }}"
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
    register: requester_group
    
  - set_fact:
      group_description: "{{ requester_group.json.description | default('') }}"
  
  - name: Create "Firewall Action" DRO entry
    uri:
      url: "{{ manageiq.api_url }}/api/generic_objects"
      method: POST
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
      body:
        action: create
        name: "{{ ipaddress }}"
        generic_object_definition:
          href: "{{ action_dro_definition_href }}"
        property_attributes:
          requester_department: "{{ group_description }}"
          requester: "{{ requester_name }}"
          requester_email: "{{ requester_email }}"
          service_id: "{{ manageiq.service.split('/')[1] }}"
        associations:
          firewall_group:
          - href: "{{ group_dro_href }}"
    register: action_dro
    
  #- debug: var=action_dro.json
    
  - set_fact:
      action_dro_href: "{{ action_dro.json.results[0].href }}"
    
  - debug: var=action_dro_href
  
  - name: Get the existing firewall_actions associations of the Firewall Group
    #  "firewall_actions": [
    #    {
    #        "href": "https://192.168.2.242/api/generic_objects/15",
    #        "id": "15",
    #        "name": "10.2.5.10",
    #        "generic_object_definition_id": "2",
    #        "created_at": "2018-04-05T16:49:34Z",
    #        "updated_at": "2018-04-05T16:49:34Z"
    #    }
    #],
    uri:
      url: "{{ group_dro_href }}?associations=firewall_actions"
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
    register: associations
    
  - debug: var=associations.json.firewall_actions

  - set_fact:
      association_hrefs: "{{ association_hrefs }} + [ '{{ item.href }}' ]"
    with_items:
      associations.json.firewall_actions
  
  # Add the new association href
  - set_fact:
      association_hrefs: "{{ association_hrefs }} + [ '{{ action_dro_href }}' ]"
    
  - name: Create the corresponding association in the Firewall Group back to the new action
    uri:
      url: "{{ group_dro_href }}"
      method: POST
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
      body:
        action: edit
        associations:
          firewall_actions:
          - href: "{{ association_hrefs }}"
    register: output 
  
  - name: Register firewall action with the service
    uri:
      url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
      method: POST
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
      body:
        action: add_resource
        resource:
          resource:
            href: "{{ action_dro_href }}"
    register: output
  
