---
- name: Create Firewall Group
  hosts: localhost

  vars:
  - firewall_group_dro_name: "{{ 'Firewall Group'|urlencode }}"

  tasks:
    
  - name: Change the service name
    uri:
      url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
      method: POST
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
      body:
        action: edit
        resource:
          name: "{{ firewall_group_name }}"
          description: "Firewall Group {{ firewall_group_name }}"
    register: output
        
  - name: Find the "Firewall Group" DRO definition
    uri:
      url: "{{ manageiq.api_url }}/api/generic_object_definitions?expand=resources&filter[]=name='{{ firewall_group_dro_name }}'"
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
    register: group_dro_definition
    
  - set_fact:
      group_dro_definition_href: "{{ group_dro_definition.json.resources[0].href }}"
  
  #- debug: var=group_dro_definition_href
  
  - name: Lookup the requesting user
    uri:
      url: "{{ manageiq.api_url }}/api/{{ manageiq.user }}"
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
    register: requester
    
  - name: Lookup the user's group
    uri:
      url: "{{ manageiq.api_url }}/api/groups/{{ requester.current_group_id }}"
      method: GET
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
    register: requester_group 
  
  - name: Create the "Firewall Group" DRO entry
    uri:
      url: "{{ manageiq.api_url }}/api/generic_objects"
      method: POST
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
      body:
        action: create
        name: "{{ firewall_group_name }}"
        generic_object_definition:
          href: "{{ group_dro_definition_href }}"
        property_attributes:
          requester_department: "{{ requester_group.description }}"
          requester: "{{ requester.name }}"
          requester_email: "{{ requester.email }}"
          service_id: "{{  manageiq.service.split('/')[1] }}"
          fw_group_provisioning_change_number: 123
    register: group_dro
    
  - set_fact:
      group_dro_href: "{{ group_dro.json.resources[0].href }}"
    
  #- debug: var=group_dro_href
    
  - name: Register firewall group with the service
    uri:
      url: "{{ manageiq.api_url }}/api/{{ manageiq.service }}"
      method: POST
      validate_certs: no
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
      body_format: json
      body:
        action: add_resource
        resource:
          resource:
            href: "{{ group_dro_href }}"
    register: output

  #- debug: var=output.json
    
